name: 'medical_records_analytics'
version: '1.0.0'
config-version: 2

profile: 'medical_records'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_records_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +tags: ['core']
      clinical:
        +tags: ['clinical']
      analytics:
        +tags: ['analytics']

vars:
  current_date: '{{ run_started_at.strftime("%Y-%m-%d") }}'