medical_records:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'secret') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'postgres') }}"
      schema: public
      threads: 4
      keepalives_idle: 0